import { component$ } from '@builder.io/qwik';

export const Drawing_2024-02-21_18.57.38.excalidraw = component$(() => {
  return <div innerHTML={'<hr>
<p>excalidraw-plugin: parsed
tags: [excalidraw]</p>
<hr>
<p>==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠==</p>
<h1>Text Elements</h1>
<p>Song 6 ^OKkc0MzQ</p>
<p>Song ^NEuuuiZf</p>
<p>List of Playlists ^oLXvEhUs</p>
<p>Playlist 2 ^OBN0oraP</p>
<p>PK ^lwtmWeDs</p>
<p>Name ^UfHBOdNB</p>
<p>Playlist 1 ^AgEZFzj0</p>
<p>Song 3 ^vcZEMeLi</p>
<p>Playlist 1 ^K38hr6HM</p>
<p>Song 1 ^MvfDIwSQ</p>
<p>whatever file ^8EU3rj9y</p>
<p>Song 3 ^93mmcGXI</p>
<p>Song 2 ^lT4uKXy7</p>
<p>All Songs ^5b6J97Sv</p>
<p>PK ^6lxXDgNv</p>
<p>PK ^HI6F6fqh</p>
<p>Song 1 ^m3qDqCy1</p>
<p>Name ^OFrFinxo</p>
<p>Author ^rJWoMkin</p>
<p>%%</p>
<h1>Drawing</h1>
<pre><code class="language-json">{
    &quot;type&quot;: &quot;excalidraw&quot;,
    &quot;version&quot;: 2,
    &quot;source&quot;: &quot;https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.0.20&quot;,
    &quot;elements&quot;: [
        {
            &quot;id&quot;: &quot;oLXvEhUs&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: -363.75,
            &quot;y&quot;: -274.2734375,
            &quot;width&quot;: 163.17984008789062,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 881938229,
            &quot;version&quot;: 39,
            &quot;versionNonce&quot;: 480970325,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;List of Playlists&quot;,
            &quot;rawText&quot;: &quot;List of Playlists&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;List of Playlists&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;gSrMcddq43svYQ_qxbfhq&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -289.75,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 138531957,
            &quot;version&quot;: 249,
            &quot;versionNonce&quot;: 472839547,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;lwtmWeDs&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: -273.75,
            &quot;y&quot;: -249.2734375,
            &quot;width&quot;: 25.47998046875,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1925342427,
            &quot;version&quot;: 107,
            &quot;versionNonce&quot;: 981562293,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;PK&quot;,
            &quot;rawText&quot;: &quot;PK&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;PK&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;UfHBOdNB&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: -185.75,
            &quot;y&quot;: -249.2734375,
            &quot;width&quot;: 49.81996154785156,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1757561627,
            &quot;version&quot;: 199,
            &quot;versionNonce&quot;: 1061719579,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Name&quot;,
            &quot;rawText&quot;: &quot;Name&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Name&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;90-Aa4OyN0xKLkkSRCdBg&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -206.75,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1113161173,
            &quot;version&quot;: 439,
            &quot;versionNonce&quot;: 568538389,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;j8p3Jbz3_EeTAGV7VqaiE&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -289.75,
            &quot;y&quot;: -154.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 578091829,
            &quot;version&quot;: 319,
            &quot;versionNonce&quot;: 1223037627,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;_4K1LgkKOT_AnRX_kOCCj&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -206.75,
            &quot;y&quot;: -154.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1626983573,
            &quot;version&quot;: 509,
            &quot;versionNonce&quot;: 776325749,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;roPAdZM6GtpBuM52AJ-A4&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -289.75,
            &quot;y&quot;: -89.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 228422133,
            &quot;version&quot;: 378,
            &quot;versionNonce&quot;: 430572379,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;Z_8PMXTOz_R7o94zp4qyu&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -206.75,
            &quot;y&quot;: -89.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 627403605,
            &quot;version&quot;: 568,
            &quot;versionNonce&quot;: 812561365,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;lb8JlAaJu1i7XNrc2z3TS&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -289.75,
            &quot;y&quot;: -18.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1755789493,
            &quot;version&quot;: 439,
            &quot;versionNonce&quot;: 1508302843,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;57virCEeyAtMlMkMloZt-&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: -206.75,
            &quot;y&quot;: -18.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1896372757,
            &quot;version&quot;: 630,
            &quot;versionNonce&quot;: 1148416309,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;K38hr6HM&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 170.25,
            &quot;y&quot;: -274.2734375,
            &quot;width&quot;: 88.419921875,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 212508565,
            &quot;version&quot;: 183,
            &quot;versionNonce&quot;: 1324422523,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563890289,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Playlist 1&quot;,
            &quot;rawText&quot;: &quot;Playlist 1&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Playlist 1&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;AgEZFzj0&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: -175.75,
            &quot;y&quot;: -204.2734375,
            &quot;width&quot;: 88.419921875,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 652067131,
            &quot;version&quot;: 284,
            &quot;versionNonce&quot;: 1740210837,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Playlist 1&quot;,
            &quot;rawText&quot;: &quot;Playlist 1&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Playlist 1&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;OBN0oraP&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: -172.75,
            &quot;y&quot;: -145.2734375,
            &quot;width&quot;: 97.23991394042969,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1385924635,
            &quot;version&quot;: 313,
            &quot;versionNonce&quot;: 746937659,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Playlist 2&quot;,
            &quot;rawText&quot;: &quot;Playlist 2&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Playlist 2&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;nSCyVqvFQ3b7GWO64W47a&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 198.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1841173019,
            &quot;version&quot;: 402,
            &quot;versionNonce&quot;: 1324771317,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;SLnrvvqZhI3y-RHrb9ZQW&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 281.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 369825467,
            &quot;version&quot;: 592,
            &quot;versionNonce&quot;: 268172763,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;plcXlEN1J2OmrdK1FqRTn&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 198.25,
            &quot;y&quot;: -154.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 59672411,
            &quot;version&quot;: 472,
            &quot;versionNonce&quot;: 2083496277,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;KZ5I-Bby4GTa5ZPhx8u_e&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 281.25,
            &quot;y&quot;: -154.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 479912955,
            &quot;version&quot;: 662,
            &quot;versionNonce&quot;: 1494583931,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;8wKpyJH2MNLn4y1G6okUd&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 198.25,
            &quot;y&quot;: -89.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1496493211,
            &quot;version&quot;: 531,
            &quot;versionNonce&quot;: 347778741,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;_HuQ8BZziuthYWpBWc2FE&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 281.25,
            &quot;y&quot;: -89.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 218652987,
            &quot;version&quot;: 721,
            &quot;versionNonce&quot;: 747930395,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;TEVZ7JkV759aGfnAOPrcC&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 198.25,
            &quot;y&quot;: -18.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1904116187,
            &quot;version&quot;: 592,
            &quot;versionNonce&quot;: 2000490517,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;Qjp2OvKspcDIqUbcUwujd&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 281.25,
            &quot;y&quot;: -18.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1873251963,
            &quot;version&quot;: 783,
            &quot;versionNonce&quot;: 1928030139,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;6lxXDgNv&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 216.25,
            &quot;y&quot;: -249.2734375,
            &quot;width&quot;: 25.47998046875,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1081826933,
            &quot;version&quot;: 274,
            &quot;versionNonce&quot;: 508014427,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563739872,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;PK&quot;,
            &quot;rawText&quot;: &quot;PK&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;PK&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;NEuuuiZf&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 328.25,
            &quot;y&quot;: -250.2734375,
            &quot;width&quot;: 42.59996032714844,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1975508213,
            &quot;version&quot;: 339,
            &quot;versionNonce&quot;: 2001587925,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song&quot;,
            &quot;rawText&quot;: &quot;Song&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;MvfDIwSQ&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 332.25,
            &quot;y&quot;: -204.2734375,
            &quot;width&quot;: 58.01995849609375,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 2075332603,
            &quot;version&quot;: 376,
            &quot;versionNonce&quot;: 917974069,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song 1&quot;,
            &quot;rawText&quot;: &quot;Song 1&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song 1&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;93mmcGXI&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 332.25,
            &quot;y&quot;: -145.2734375,
            &quot;width&quot;: 66.21995544433594,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 425420981,
            &quot;version&quot;: 430,
            &quot;versionNonce&quot;: 348691867,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song 3&quot;,
            &quot;rawText&quot;: &quot;Song 3&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song 3&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;5b6J97Sv&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 624.25,
            &quot;y&quot;: -292.2734375,
            &quot;width&quot;: 87.09992980957031,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 547910485,
            &quot;version&quot;: 301,
            &quot;versionNonce&quot;: 293560219,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563738362,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;All Songs&quot;,
            &quot;rawText&quot;: &quot;All Songs&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;All Songs&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;gKQSQF72jTZXRJ5ZASYfQ&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 651.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 225800187,
            &quot;version&quot;: 548,
            &quot;versionNonce&quot;: 1121313077,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563735458,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;3aKvTdkyYAr_yJCCsUjZC&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 734.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 291.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1705033045,
            &quot;version&quot;: 1022,
            &quot;versionNonce&quot;: 1339305595,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563779649,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;W-7f2zPrAT4r3CpMPu928&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 651.25,
            &quot;y&quot;: -154.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1725675675,
            &quot;version&quot;: 595,
            &quot;versionNonce&quot;: 1347285653,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563735458,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;bGIvPNI8lzblKMEk4L_qD&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 734.25,
            &quot;y&quot;: -154.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1964586037,
            &quot;version&quot;: 943,
            &quot;versionNonce&quot;: 646301435,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563775407,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;bS28jl4oNCiLo6a6oSbh0&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 651.25,
            &quot;y&quot;: -89.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 430959931,
            &quot;version&quot;: 654,
            &quot;versionNonce&quot;: 192731125,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563735458,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;9HvNZ4XprSxkiIVTEjaRh&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 735.25,
            &quot;y&quot;: -89.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1792649211,
            &quot;version&quot;: 1005,
            &quot;versionNonce&quot;: 1237921691,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: [],
            &quot;updated&quot;: 1708563775407,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;vxQcwVzo_IuiSWn092F4X&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 651.25,
            &quot;y&quot;: -18.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 424971739,
            &quot;version&quot;: 715,
            &quot;versionNonce&quot;: 1047007573,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563735458,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;jqfARXmGLEoNWWqEhc5S7&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 735.25,
            &quot;y&quot;: -18.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 793322043,
            &quot;version&quot;: 1065,
            &quot;versionNonce&quot;: 1305904187,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563775407,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;m3qDqCy1&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 769.25,
            &quot;y&quot;: -204.2734375,
            &quot;width&quot;: 58.01995849609375,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1120314741,
            &quot;version&quot;: 604,
            &quot;versionNonce&quot;: 779638875,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563781810,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song 1&quot;,
            &quot;rawText&quot;: &quot;Song 1&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song 1&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;lT4uKXy7&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 770.25,
            &quot;y&quot;: -140.2734375,
            &quot;width&quot;: 66.83995056152344,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 706727669,
            &quot;version&quot;: 665,
            &quot;versionNonce&quot;: 2005463419,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563775407,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song 2&quot;,
            &quot;rawText&quot;: &quot;Song 2&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song 2&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;vcZEMeLi&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 771.25,
            &quot;y&quot;: -74.2734375,
            &quot;width&quot;: 66.21995544433594,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1376850229,
            &quot;version&quot;: 730,
            &quot;versionNonce&quot;: 369297947,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563775407,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song 3&quot;,
            &quot;rawText&quot;: &quot;Song 3&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song 3&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;OKkc0MzQ&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 332.25,
            &quot;y&quot;: -75.2734375,
            &quot;width&quot;: 65.39994812011719,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 159707995,
            &quot;version&quot;: 485,
            &quot;versionNonce&quot;: 564791803,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song 6&quot;,
            &quot;rawText&quot;: &quot;Song 6&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song 6&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;HI6F6fqh&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 671.25,
            &quot;y&quot;: -249.2734375,
            &quot;width&quot;: 25.47998046875,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 751340059,
            &quot;version&quot;: 397,
            &quot;versionNonce&quot;: 1232140565,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563742591,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;PK&quot;,
            &quot;rawText&quot;: &quot;PK&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;PK&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;Us_iuohU5mpP4uzNtXpm3&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1034.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1085003131,
            &quot;version&quot;: 1178,
            &quot;versionNonce&quot;: 1354929077,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563814158,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;OFrFinxo&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 782.25,
            &quot;y&quot;: -251.2734375,
            &quot;width&quot;: 49.81996154785156,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 489817531,
            &quot;version&quot;: 647,
            &quot;versionNonce&quot;: 187074421,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563785501,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Name&quot;,
            &quot;rawText&quot;: &quot;Name&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Name&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;rJWoMkin&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 1076.25,
            &quot;y&quot;: -251.2734375,
            &quot;width&quot;: 65.33993530273438,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 546595707,
            &quot;version&quot;: 756,
            &quot;versionNonce&quot;: 1166514491,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563803945,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Author&quot;,
            &quot;rawText&quot;: &quot;Author&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Author&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;8EU3rj9y&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 1216.25,
            &quot;y&quot;: -251.2734375,
            &quot;width&quot;: 127.93988037109375,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 691627099,
            &quot;version&quot;: 963,
            &quot;versionNonce&quot;: 1890298971,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563904353,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;whatever file&quot;,
            &quot;rawText&quot;: &quot;whatever file&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;whatever file&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;fIUymmGU2-DHvorKRcZpt&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1211.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 19492379,
            &quot;version&quot;: 1256,
            &quot;versionNonce&quot;: 318788885,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563814158,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;oKMKg8O5Ly1bqXcp1r4aH&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1034.25,
            &quot;y&quot;: -151.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1370008981,
            &quot;version&quot;: 1247,
            &quot;versionNonce&quot;: 2092065339,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563816068,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;yTaJg_oAA1mfVvee1w0bG&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1211.25,
            &quot;y&quot;: -151.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 667431669,
            &quot;version&quot;: 1325,
            &quot;versionNonce&quot;: 1044407003,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563816068,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;rpyYKgyU3DzeFn98XJ_U0&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1034.25,
            &quot;y&quot;: -85.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 695829339,
            &quot;version&quot;: 1304,
            &quot;versionNonce&quot;: 1733768149,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563817203,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;KRRlZdIH-jj11_iqbe5ds&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1211.25,
            &quot;y&quot;: -85.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1137074171,
            &quot;version&quot;: 1382,
            &quot;versionNonce&quot;: 172749109,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563817203,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;6QIOu9Z-Ozrs4_NbBETJ0&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1034.25,
            &quot;y&quot;: -20.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 562049275,
            &quot;version&quot;: 1361,
            &quot;versionNonce&quot;: 789945173,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563817887,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;7L7FzulbBHCGGuzQXy2oX&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1211.25,
            &quot;y&quot;: -20.2734375,
            &quot;width&quot;: 155.99999999999994,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1508417973,
            &quot;version&quot;: 1439,
            &quot;versionNonce&quot;: 751921333,
            &quot;isDeleted&quot;: false,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563817887,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;OjKkzjcV&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 304.25,
            &quot;y&quot;: -274.2734375,
            &quot;width&quot;: 25.47998046875,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1004811419,
            &quot;version&quot;: 243,
            &quot;versionNonce&quot;: 296502645,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;PK&quot;,
            &quot;rawText&quot;: &quot;PK&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;PK&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;cNEDwLfY&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 363.25,
            &quot;y&quot;: -306.2734375,
            &quot;width&quot;: 10,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 604351899,
            &quot;version&quot;: 4,
            &quot;versionNonce&quot;: 1213920507,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;&quot;,
            &quot;rawText&quot;: &quot;&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;KycuwWqB&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 875.25,
            &quot;y&quot;: -76.2734375,
            &quot;width&quot;: 10,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 724213,
            &quot;version&quot;: 4,
            &quot;versionNonce&quot;: 1188788251,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727561,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;&quot;,
            &quot;rawText&quot;: &quot;&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;center&quot;,
            &quot;verticalAlign&quot;: &quot;middle&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: &quot;9HvNZ4XprSxkiIVTEjaRh&quot;,
            &quot;originalText&quot;: &quot;&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;GkwupNSt&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 1166.25,
            &quot;y&quot;: -274.2734375,
            &quot;width&quot;: 42.59996032714844,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 417777595,
            &quot;version&quot;: 436,
            &quot;versionNonce&quot;: 1298963765,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563767537,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;Song&quot;,
            &quot;rawText&quot;: &quot;Song&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;Song&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;qEQXcYj4KV1tzkc-qZmjC&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1160.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 2031481595,
            &quot;version&quot;: 769,
            &quot;versionNonce&quot;: 52346011,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563767537,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;A3-rVTtm0borWtvCUIHs8&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 1243.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 292,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 829676443,
            &quot;version&quot;: 959,
            &quot;versionNonce&quot;: 1353526933,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563767537,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;UaQpMjRoFzovNhXtLow3P&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 651.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 219390997,
            &quot;version&quot;: 527,
            &quot;versionNonce&quot;: 1225131835,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563727562,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;KsgCxr_nyFVjFrjLOCNLt&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 732.25,
            &quot;y&quot;: -220.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1960834133,
            &quot;version&quot;: 625,
            &quot;versionNonce&quot;: 1584791349,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563772704,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;DxqeuIDz9UrrJMwl-Fsxg&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 732.25,
            &quot;y&quot;: -154.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 458282709,
            &quot;version&quot;: 672,
            &quot;versionNonce&quot;: 1800698523,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563772704,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;aB1GcR59V1gDV_m6ypGW-&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 732.25,
            &quot;y&quot;: -89.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1129696091,
            &quot;version&quot;: 731,
            &quot;versionNonce&quot;: 2117750933,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563772704,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;aFBx-AKN9FrY9oSTCwR6Z&quot;,
            &quot;type&quot;: &quot;rectangle&quot;,
            &quot;x&quot;: 732.25,
            &quot;y&quot;: -18.2734375,
            &quot;width&quot;: 66,
            &quot;height&quot;: 51,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: {
                &quot;type&quot;: 3
            },
            &quot;seed&quot;: 1427179541,
            &quot;version&quot;: 792,
            &quot;versionNonce&quot;: 1438674747,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563772704,
            &quot;link&quot;: null,
            &quot;locked&quot;: false
        },
        {
            &quot;id&quot;: &quot;j5dpneSV&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 745.25,
            &quot;y&quot;: -249.2734375,
            &quot;width&quot;: 23.739990234375,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1422948859,
            &quot;version&quot;: 451,
            &quot;versionNonce&quot;: 1697140053,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563770490,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;FK&quot;,
            &quot;rawText&quot;: &quot;FK&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;FK&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;7PyV8reP&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 1173.25,
            &quot;y&quot;: -249.2734375,
            &quot;width&quot;: 23.739990234375,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1532245045,
            &quot;version&quot;: 552,
            &quot;versionNonce&quot;: 1056076091,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563767537,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;FK&quot;,
            &quot;rawText&quot;: &quot;FK&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;FK&quot;,
            &quot;lineHeight&quot;: 1.25
        },
        {
            &quot;id&quot;: &quot;YpbwKlJX&quot;,
            &quot;type&quot;: &quot;text&quot;,
            &quot;x&quot;: 241.25,
            &quot;y&quot;: -274.2734375,
            &quot;width&quot;: 10,
            &quot;height&quot;: 25,
            &quot;angle&quot;: 0,
            &quot;strokeColor&quot;: &quot;#1e1e1e&quot;,
            &quot;backgroundColor&quot;: &quot;transparent&quot;,
            &quot;fillStyle&quot;: &quot;solid&quot;,
            &quot;strokeWidth&quot;: 2,
            &quot;strokeStyle&quot;: &quot;solid&quot;,
            &quot;roughness&quot;: 1,
            &quot;opacity&quot;: 100,
            &quot;groupIds&quot;: [],
            &quot;frameId&quot;: null,
            &quot;roundness&quot;: null,
            &quot;seed&quot;: 1525182043,
            &quot;version&quot;: 2,
            &quot;versionNonce&quot;: 73700917,
            &quot;isDeleted&quot;: true,
            &quot;boundElements&quot;: null,
            &quot;updated&quot;: 1708563886427,
            &quot;link&quot;: null,
            &quot;locked&quot;: false,
            &quot;text&quot;: &quot;&quot;,
            &quot;rawText&quot;: &quot;&quot;,
            &quot;fontSize&quot;: 20,
            &quot;fontFamily&quot;: 1,
            &quot;textAlign&quot;: &quot;left&quot;,
            &quot;verticalAlign&quot;: &quot;top&quot;,
            &quot;baseline&quot;: 18,
            &quot;containerId&quot;: null,
            &quot;originalText&quot;: &quot;&quot;,
            &quot;lineHeight&quot;: 1.25
        }
    ],
    &quot;appState&quot;: {
        &quot;theme&quot;: &quot;dark&quot;,
        &quot;viewBackgroundColor&quot;: &quot;#ffffff&quot;,
        &quot;currentItemStrokeColor&quot;: &quot;#1e1e1e&quot;,
        &quot;currentItemBackgroundColor&quot;: &quot;transparent&quot;,
        &quot;currentItemFillStyle&quot;: &quot;solid&quot;,
        &quot;currentItemStrokeWidth&quot;: 2,
        &quot;currentItemStrokeStyle&quot;: &quot;solid&quot;,
        &quot;currentItemRoughness&quot;: 1,
        &quot;currentItemOpacity&quot;: 100,
        &quot;currentItemFontFamily&quot;: 1,
        &quot;currentItemFontSize&quot;: 20,
        &quot;currentItemTextAlign&quot;: &quot;left&quot;,
        &quot;currentItemStartArrowhead&quot;: null,
        &quot;currentItemEndArrowhead&quot;: &quot;arrow&quot;,
        &quot;scrollX&quot;: 395.25,
        &quot;scrollY&quot;: 645.7265625,
        &quot;zoom&quot;: {
            &quot;value&quot;: 1
        },
        &quot;currentItemRoundness&quot;: &quot;round&quot;,
        &quot;gridSize&quot;: null,
        &quot;gridColor&quot;: {
            &quot;Bold&quot;: &quot;#C9C9C9FF&quot;,
            &quot;Regular&quot;: &quot;#EDEDEDFF&quot;
        },
        &quot;currentStrokeOptions&quot;: null,
        &quot;previousGridSize&quot;: null,
        &quot;frameRendering&quot;: {
            &quot;enabled&quot;: true,
            &quot;clip&quot;: true,
            &quot;name&quot;: true,
            &quot;outline&quot;: true
        }
    },
    &quot;files&quot;: {}
}
</code></pre>
<p>%%</p>
'}></div>;
});